### ISSUE TITLE
Missing important information in the meta.yaml

### ISSUE THREAD

**Issue by varlackc** [conda-forge/hdf4-feedstock#37]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

The about section in the recipe/meta.yaml file is missing some key information such as the dev_url or doc_url.

**Comment by ocefpaf** [comment]
> The about section in the recipe/meta.yaml file is missing some key information such as the dev_url or doc_url.

Those are optional but nice to have. If you want please send a PR to add them.

**Comment by varlackc** [comment]
A pull request was created in order to address the problem.
 
https://github.com/conda-forge/hdf4-feedstock/pull/38
