### ISSUE TITLE
HDF4 has copies of ncdump and ncgen

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/hdf4-feedstock#5]
So this package comes with `ncgen` and `ncgen` copies of its own; these prevent libnetcdf from being able to have its own copies, since conda build (I think) detects these binaries as already existing.

**Comment by ocefpaf** [comment]
I thought that [this](https://github.com/conda-forge/hdf4-feedstock/blob/master/recipe/build.sh#L21) was enough to avoid this name clash. Apparently we need a better solution... Working on it.
